SELECT
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.TOTAL_BOOK_COUNT) AS TOTAL_SALES
FROM
    BOOK B JOIN 
    (SELECT BOOK_ID, SUM(SALES) AS TOTAL_BOOK_COUNT
    FROM BOOK_SALES
     WHERE SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
     GROUP BY BOOK_ID
     
    ) S ON B.BOOK_ID = S.BOOK_ID 
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY
    A.AUTHOR_ID, B.CATEGORY DESC;