SELECT
    THIRD_GEN.ID
FROM
    ECOLI_DATA AS THIRD_GEN JOIN
    (SELECT SECOND_GEN.ID
    FROM ECOLI_DATA AS SECOND_GEN JOIN 
        (SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL) AS FIRST_GEN ON SECOND_GEN.PARENT_ID = FIRST_GEN.ID
    ) T ON THIRD_GEN.PARENT_ID = T.ID    
ORDER BY
    ID;
