-- 코드를 입력하세요
-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리
-- 보호 기간 = O.DATETIME - I.DATETIME
SELECT
    O.ANIMAL_ID, O.NAME
FROM
    ANIMAL_OUTS O
JOIN 
    ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY
     O.DATETIME - I.DATETIME DESC
LIMIT 2;