SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
   AND NOT (
        R.END_DATE < '2022-11-01'
        OR R.START_DATE > '2022-11-30'
   )
JOIN (
    SELECT CAR_TYPE, MAX(DISCOUNT_RATE) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
    GROUP BY CAR_TYPE
) D ON C.CAR_TYPE = D.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND R.CAR_ID IS NULL
    AND FLOOR(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) >= 500000
    AND FLOOR(C.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) < 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;
