-- 코드를 입력하세요
# 메인 쿼리 - 서브쿼리와 MAX_FAVORITES 와 FAVORITES가 동일하고 FOOD_TYPE이 동일한 인스턴스 출력
SELECT
    I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM
    REST_INFO I JOIN
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) T ON I.FAVORITES = T.MAX_FAVORITES AND I.FOOD_TYPE = T.FOOD_TYPE
ORDER BY
    FOOD_TYPE DESC;
# 서브 쿼리 - MAX_FAVORITES 도출 찾기    
# SELECT
#     FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORIES 
# FROM
#     REST_INFO
# GROUP BY
#    FOOD_TYPE
