SELECT
    ID, 
    CASE
        WHEN GROUP_NUMBER = 1 THEN 'CRITICAL'
        WHEN GROUP_NUMBER = 2 THEN 'HIGH'
        WHEN GROUP_NUMBER = 3 THEN 'MEDIUM'
        ELSE 'LOW' END AS COLONY_NAME
FROM
    (SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS GROUP_NUMBER
    FROM ECOLI_DATA) T
ORDER BY
    ID;