SELECT
    ID, 
    CASE
        WHEN PARTITIONED_NUMBER = 1 THEN 'CRITICAL'
        WHEN PARTITIONED_NUMBER = 2 THEN 'HIGH'
        WHEN PARTITIONED_NUMBER = 3 THEN 'MEDIUM'
        ELSE 'LOW' END AS COLONY_NAME
FROM
    (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PARTITIONED_NUMBER
    FROM ECOLI_DATA) T
ORDER BY
    ID