-- 코드를 입력하세요
SELECT
    U.USER_ID, U.NICKNAME,CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ', U.STREET_ADDRESS2) AS 전체주소,
    INSERT(INSERT(U.TLNO,4,0,'-'),9,0,'-') AS 전화번호
FROM
    USED_GOODS_USER U
JOIN
    USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
GROUP BY
    B.WRITER_ID
HAVING
    COUNT(*) >= 3
ORDER BY
    U.USER_ID DESC;