-- 코드를 입력하세요
SELECT
    I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, T.SCORE
FROM
    REST_INFO I JOIN
    (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID) T ON I.REST_ID = T.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
ORDER BY
    T.SCORE DESC, FAVORITES DESC

-- SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
--     FROM REST_REVIEW
--     GROUP BY REST_ID
    

    