-- 서울에 위치한 식당
SELECT
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, T.AVG_SCORE AS SCORE
FROM
    REST_INFO I JOIN
    (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS AVG_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID) T ON I.REST_ID = T.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
ORDER BY
    SCORE DESC, I.FAVORITES DESC
    
-- SELECT
--     REST_ID , ROUND(AVG(REVIEW_SCORE), 2) AS AVG_SCORE
-- FROM
--     REST_REVIEW
-- GROUP BY
--     REST_ID

-- SELECT ADDRESS
-- FROM REST_INFO
-- WHERE ADDRESS LIKE '서울%'