-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT I.USER_ID) AS USERS
FROM
    ONLINE_SALE S JOIN USER_INFO I 
    ON S.USER_ID = I.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY
    YEAR, MONTH, GENDER