-- 1. USER_INFO 테이블에서 21년도에 가입한 사람들 추리고 USER_ID SELECT
SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT S.USER_ID) / 
          (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021'), 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE S JOIN 
    (SELECT USER_ID
     FROM USER_INFO 
     WHERE EXTRACT(YEAR FROM JOINED) = '2021') T ON S.USER_ID = T.USER_ID
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY
    YEAR, MONTH
-- SELECT USER_ID,
--         (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021') AS TOTAL_COUNT
--      FROM USER_INFO 
--      WHERE EXTRACT(YEAR FROM JOINED) = '2021'