-- 1. USER_INFO 테이블에서 21년 가입 회원 ID를 찾는다
-- 2. ID로 ONLINE_SALE 테이블에서 USER_ID 그룹 후 몇 명의 유저가 구매했는지 찾는다. -> PURCHASED_USERS
-- SELECT USER_ID
-- FROM USER_INFO
-- WHERE EXTRACT(YEAR FROM JOINED) = '2021'

SELECT 
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE S JOIN 
    (SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021) T ON S.USER_ID = T.USER_ID
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY
    MONTH

