-- 코드를 입력하세요
SELECT
    H.FLAVOR
FROM 
    FIRST_HALF H JOIN 
    (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
     GROUP BY FLAVOR
     ORDER BY SHIPMENT_ID
    ) AS J
    ON H.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY
    (H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3;
    
    
# SELECT SHIPMENT_ID, FLAVOR
# FROM JULY
# # GROUP BY FLAVOR
# ORDER BY SHIPMENT_ID
    
