-- 코드를 입력하세요
-- STATUS = 'DONE'
-- SUM(PRICE) >= 700000
SELECT
    U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER U
JOIN 
    USED_GOODS_BOARD B ON U.USER_ID = B.WRITER_ID
WHERE
    B.STATUS = 'DONE'
GROUP BY
    B.WRITER_ID
HAVING
    SUM(PRICE) >= 700000
ORDER BY
    SUM(PRICE);
    