-- 사원별 성과금 정보
SELECT
    E.EMP_NO, E.EMP_NAME, T.GRADE,
    CASE WHEN T.GRADE = 'S' THEN E.SAL * 0.2
        WHEN T.GRADE = 'A' THEN E.SAL * 0.15
        WHEN T.GRADE = 'B' THEN E.SAL * 0.1
        ELSE E.SAL * 0 END AS BONUS
FROM
    HR_EMPLOYEES E JOIN 
    (SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE,
     CASE WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96 THEN 'A'
        WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90 THEN 'B'
        ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO) T ON E.EMP_NO = T.EMP_NO
    
    


