# SELECT EMP_NO,
#     CASE WHEN AVG(SCORE) >= 96 THEN 'S'
#         WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96  THEN 'A'
#         WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90  THEN 'B'
#         ELSE 'C' END AS GRADE
#         , 
#     CASE WHEN AVG(SCORE) >= 96 THEN 0.2
#         WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96  THEN 0.15
#         WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90  THEN 0.1
#         ELSE 0 END AS RATE
# FROM HR_GRADE
# GROUP BY EMP_NO

SELECT 
    E.EMP_NO, E.EMP_NAME, GRADE, E.SAL * T.RATE AS BONUS
FROM
    HR_EMPLOYEES E JOIN
    (SELECT EMP_NO,
    CASE WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96  THEN 'A'
        WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90  THEN 'B'
        ELSE 'C' END AS GRADE
        , 
    CASE WHEN AVG(SCORE) >= 96 THEN 0.2
        WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96  THEN 0.15
        WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90  THEN 0.1
        ELSE 0 END AS RATE
    FROM HR_GRADE
    GROUP BY EMP_NO) T ON E.EMP_NO = T.EMP_NO
ORDER BY
    E.EMP_NO;