# 1. 리뷰 가장 많이 쓴 사람 찾기
# SELECT 
#     MEMBER_ID, COUNT(*) AS REVIEW_COUNT
# FROM 
#     REST_REVIEW
# GROUP BY
#     MEMBER_ID
# ORDER BY
#     REVIEW_COUNT DESC
# LIMIT 1
# 2. MEMBER_ID를 활용해 REST_REVIEW 와 MEMBER_PROFILE 조인
SELECT
    M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIRE_DATE
FROM
    MEMBER_PROFILE M
JOIN
    REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE 
    R.MEMBER_ID = (SELECT 
    MEMBER_ID
FROM 
    REST_REVIEW
GROUP BY
    MEMBER_ID
ORDER BY
    COUNT(*) DESC
LIMIT 1)
ORDER BY
    R.REVIEW_DATE,
    R.REVIEW_TEXT;