-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 CAR_ID 구하기
# SELECT
#     CAR_ID
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
#     START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
# GROUP BY
#     CAR_ID
# HAVING 
#     COUNT(*) >= 5



-- 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 구하기

SELECT
    MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY C JOIN 
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
     GROUP BY CAR_ID HAVING COUNT(*) >= 5
    ) T ON C.CAR_ID = T.CAR_ID
WHERE
    C.START_DATE >= '2022-08-01' AND C.START_DATE < '2022-11-01'
GROUP BY
    -- 1. 월별
    MONTH(C.START_DATE),
    -- 2. 자동차 ID 별
    C.CAR_ID
ORDER BY
    MONTH(C.START_DATE), C.CAR_ID DESC;