# 메인쿼리 - 서브쿼리의 CAR_ID로 조인된 CAR_ID의 월별 대여 횟수 반환
SELECT
    MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN
    (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= "2022-08-01" AND START_DATE < "2022-11-01"
     GROUP BY CAR_ID HAVING COUNT(*) >= 5
    ) T ON H.CAR_ID = T.CAR_ID
WHERE
    START_DATE >= "2022-08-01" AND START_DATE < "2022-11-01"
GROUP BY
    MONTH(H.START_DATE), H.CAR_ID
ORDER BY
    MONTH(H.START_DATE), H.CAR_ID DESC;

# 서브쿼리 - 22/8 ~ 22/10 기간 중 총 대여 횟수 5회 이상인 CAR_ID
# SELECT
#     CAR_ID
# FROM
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
#     END_DATE >= "2022-08-01" AND START_DATE < "2022-11-01" 
# GROUP BY
#     CAR_ID
# HAVING
#     COUNT(*) >= 5