-- 코드를 작성해주세요
# 1. 연도별 최대값 구하기
# SELECT
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     MAX(SIZE_OF_COLONY) AS MAX_SIZE
# FROM
#     ECOLI_DATA
# GROUP BY
#     YEAR(DIFFERENTIATION_DATE)
    
# 2. 메인 쿼리에 적용
SELECT
    YEAR(T1.DIFFERENTIATION_DATE) AS YEAR,
    (V1.MAX_SIZE - T1.SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA T1
JOIN
    (SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
    ) V1 ON YEAR(T1.DIFFERENTIATION_DATE) = V1.YEAR
ORDER BY
    YEAR,
    YEAR_DEV;
    