-- 코드를 작성해주세요
# 1. 타입별 가장 길이가 긴 레코드를 찾아 임시 테이블 생성하기
# SELECT
#     FISH_TYPE, MAX(LENGTH) AS LENGTH
# FROM
#     FISH_INFO
# GROUP BY
#     FISH_TYPE

    
SELECT
    I1.ID, N.FISH_NAME, I1.LENGTH
FROM
    FISH_INFO I1
JOIN
    (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) I2 ON I1.FISH_TYPE = I2.FISH_TYPE
JOIN
    FISH_NAME_INFO N ON N.FISH_TYPE = I1.FISH_TYPE
WHERE
    I1.LENGTH = I2.LENGTH
ORDER BY
    ID;