# 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회
SELECT 
    SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM 
    HR_EMPLOYEES E
JOIN 
    HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY
    E.EMP_NO
HAVING
    SUM(SCORE) = (
        SELECT MAX(SUM_SCORE)
        FROM (
            SELECT SUM(G2.SCORE) AS SUM_SCORE
            FROM HR_GRADE G2
            GROUP BY G2.EMP_NO
        ) TEMP
    )