-- 코드를 입력하세요
SELECT
    P1.CATEGORY, P2.MAX_PRICE, P1.PRODUCT_NAME
FROM
    FOOD_PRODUCT P1 JOIN
    (SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
     GROUP BY CATEGORY
    ) P2 ON P1.PRICE = P2.MAX_PRICE
WHERE
    CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY
    CATEGORY
ORDER BY
    P2.MAX_PRICE DESC;