-- 1. CATEGORY 별 그룹화 하고 각 그룹별 가장 높은 금액 SELECT
# SELECT MAX(PRICE) AS MAX_PRICE
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY

SELECT
    F.CATEGORY, T.MAX_PRICE, F.PRODUCT_NAME
FROM
    FOOD_PRODUCT F JOIN 
    (SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) T ON F.PRICE = T.MAX_PRICE
WHERE
    F.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY
    F.CATEGORY
ORDER BY
    T.MAX_PRICE DESC;
    
    
